"""empty message

Revision ID: 324fc54fa9ef
Revises: 6f306560908d
Create Date: 2025-04-07 23:50:06.506990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '324fc54fa9ef'
down_revision = '6f306560908d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###
